# config.yaml

# ---------------- ROS & 传感器配置 ----------------
ros:
  camera_names: ["head", "left_arm", "right_arm"]

robot:
  ip: "192.168.100.100"
  port: 12345
  
  reset_joints: [
    1.0093586444854736, -1.3492074012756348, -1.134690761566162,
    -1.9343969821929932, -0.1084338054060936, 0.2987898588180542, 0.3599584102630615
  ]

  # 夹爪参数
  gripper:
    open_val: 0.65       # 物理最大张开值
    close_val: 0.0       # 物理闭合值
    threshold: 0.045     # 状态机：判定为 "已张开/放置" 的阈值
    action_limit: 0.065  # 动作映射时的最大值限制
    offset: 0.004        # 动作映射时的微调偏移量 (Magic Number extraction)
    force: 11            # 夹持力度

# ---------------- client inference config ----------------
inference:
  ws_url: "ws://127.0.0.1:8000"
  ws_url_tray: "ws://127.0.0.1:9000"
  max_steps: 200
  infer_freq: 20
  action_horizon: 15
  
  task1_prompt: "place the spider board in the designated position."
  task2_prompt: "place the spider board on the tray."
  
  # 数据记录路径
  output_dir: "/home/abc/galbot_records/5"

place_spider_on_workshop:
  init_leg_joints: [0.28055068850517273, 1.1670596599578857,0.936447262763977, 0.01073786523193121]
  init_place_left_arm_joints: [1.1878761053085327, -0.9060072898864746, -1.0423855781555176, -1.614225149154663, -2.378556966781616, 0.48993828892707825, -0.18479542434215546]
  init_place_right_arm_joints: [-1.22972571849823,-0.11684628576040268,0.3694494962692261,2.3407340049743652,1.2378990650177002,-0.31537747383117676,-0.08767660707235336]
  

pick_spider_from_workshop:
  pick_left_arm_joints_wp1: [1.1309033632278442,-1.2163511514663696,-0.9731884598731995,-1.6327046155929565,-2.100332498550415,0.5202825665473938,-0.1686650961637497]
  pick_left_arm_joints_wp2: [1.0362995862960815,-1.3864561319351196,-1.08627188205719,-1.7218927145004272,-2.0052731037139893,0.665027916431427,-0.3748425841331482]
  lift_spider_joints: [1.0765659809112549,-1.366226077079773,-1.1555649042129517,-1.8238531351089478,-2.093427896499634,0.714090883731842,-0.3705752193927765]


place_spider_on_tray:
  init_place_arm_joints: [0.4798729717731476,-0.5390745401382446,-0.3708632290363312,-1.6466550827026367,-2.6352357864379883,0.5366764664649963,-0.20217368006706238]
  init_leg_joints: [0.6000021696090698, 1.7999465465545654,1.1799787282943726, -1.5708202123641968]
  init_place_arm_joints1: [1.1606961488723755,-1.1515628099441528,-1.1617991924285889,-1.9652177095413208,-1.8919733762741089,0.04021936282515526,-0.044842738658189774]
  right_arm_obs: [-1.1864625215530396,0.2816786468029022,0.47515013813972473,2.3794925212860107,1.0567461252212524,-0.706924557685852,-0.10598859935998917]